#!/bin/bash
set -e

cd $(dirname $0)/..

ARCH=${ARCH:?"ARCH not set"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"
CONTENT=$(</proc/sys/kernel/random/uuid)

rm -rf dist/artifacts

mkdir -p build/${CONTENT}
mkdir -p dist/artifacts

if [ ! -e bin/host-api ]; then
    ./scripts/build
fi

cp -rf apply.sh bin build/${CONTENT}

cd build

sha1sum -b $(find ${CONTENT} -type f) > ${CONTENT}/SHA1SUMS
sha1sum ${CONTENT}/SHA1SUMS > ${CONTENT}/SHA1SUMSSUM
sha256sum -b $(find ${CONTENT} -type f) > ${CONTENT}/SHA256SUMS
sha256sum ${CONTENT}/SHA256SUMS > ${CONTENT}/SHA256SUMSSUM

ARTIFACT_PATH="../dist/artifacts/host-api-${ARCH}.tar.gz"

tar czf ${ARTIFACT_PATH} ${CONTENT}
echo Created ${ARTIFACT_PATH}
