#!/bin/bash
set -e

cd $(dirname $0)/..

if [ -x "$(which wrapdocker)" ]; then
    wrapdocker > /tmp/docker.log 2>&1
    docker ps -q
fi

if [[ ! -e /host/proc/ ]]; then
    mkdir -p /host
    ln -s /proc /host/proc
fi

docker pull zambon/busybox-multi:1
docker tag zambon/busybox-multi:1 busybox:1

docker run -i -d busybox:1

go test -timeout 30s -v ./...

echo OK
